<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="1_CreationalPatterns\AbstractFactory\" />
    <Folder Include="2_StructuralPatterns\" />
    <Folder Include="3_BehavioralPatterns\" />
  </ItemGroup>

</Project>
